### PR TITLE
feat: loan partner

### PR DESCRIPTION
**Pull request by anandbaburajan**
Loan Partner doctype corresponds to the co-lender entity in the co-lending arrangement.

### CODE REVIEW

**Comment by bosue** [comment]
Nicely developing, new feature!

A bit overwhelming though. I can imagine you‘re modeling it to your client needs. But how about going a step further and flexibilizing it quite a bit?

I‘m wondering how all these individual earnings and risk sharing features would match our needs with our own partners, including:
- financial intermediaries
- commissioned sales agents
- white label resellers
- refinancing partners
- risk taking partners (forfaiters, guarantee banks)
- insurances
- …
each being quite differently integrated into the business model, but with quite some overlap of what I can already see in the current _Loan Partner_ doctype. So a _Loan Partner Type_ doctype, allowing to pick (and preset) the relevant areas of cooperations, would be nice.

Then again, we may have different cooperation models / contracts with the same _Loan Partner_, based on segment or whatever. So I wonder if the doctype you‘re working on might be called _Loan Partnership_, with a 1:n relation to the partnering Party.

Speaking of _Parties_, it would still be wonderful if ERPNext had a concept of all-purpose parties that may be tied to Customer, Supplier, Employee, Loan partner etc. roles (and with “roles” I mean party roles, not user roles, of course), and even several of them at the same time. This would be so incredibly flexible for all kinds of integration, but is out of scope here, of course.

All in all, what I’d love to see is generalization, generalization and again generalization. While, of course, the financial services company you’re working with will want specificity, specificity, specificity. I wonder if one and the other may be combined…

Obviously you’re not in the position of catering to our specific usecase. Noone expects that. But I can imagine, if this app is modeled to work for two or three, maybe a couple of quite different companies, then it’s going to work for all or most other financial services companies as well!

I will provide you with reviews from time to time, while this module is developing. We may also talk about how we can further support your work the next couple of months. Let’s see how things are going…

Sorry for the overly lengthy comment, but best regards!

**Comment by anandbaburajan** [comment]
> I‘m wondering how all these individual earnings and risk sharing features would match our needs with our own partners .... on might be called _Loan Partnership_, with a 1:n relation to the partnering Party.

The doctype is modelled for co-lenders (risk sharing entities) so we can call it _Loan Co-lender_  too to be more specific, if _Loan Partner_ is ambiguous. What do you think?

> I can imagine you‘re modeling it to your client needs

Mostly, and client-specific code goes to a custom app.

> What I’d love to see is generalization, generalization and again generalization

Yep, us too. These PRs (with the `Project-K` label) will be WIP until we're sure that they're generic enough to go in.

> I will provide you with reviews from time to time, while this module is developing.

We appreciate it.

> Sorry for the overly lengthy comment

We like your lengthy comments :D

**Comment by bosue** [comment]
> The doctype is modeled for co-lenders (risk-sharing entities), so we could also call it “Loan Co-lender” to be more specific if “Loan Partner” is ambiguous. What do you think?

“Co-lenders” is a quite specific concept. I’ve never seen it in the retail loan sector, only for very large loans. However, Indian regulation seems to have formalized this concept for micro-loans as well, following the U.S. model.

There are many related concepts:
- Financial intermediaries and sales agents who are commissioned by a share of the markup but are also given a stake in extra earnings like insurance premiums. They also participate in write-downs.
- Risk-taking partners (forfaiters, guarantee banks) who are given a stake both in write-downs and net recovery proceeds but also share pre-closure and documentation charges.
- Mere refinancing partners who won’t take any risk but will refinance the loan at the refinancing rate and still share pre-closure and documentation charges.
- White-label resellers with various earnings- and risk-sharing models, possibly encompassing all of the above to a certain degree.
- etc.

I’m not a fan of creating various doctypes for Co-lending Partner, Sales Partner, Risk-taking Partner, Refinance Partner, Loan Reseller, and so on. You’ll never capture all use-cases and won’t be flexible enough, while duplicating code, siloing data in similar doctypes, and struggling with code maintenance.

Instead, I envision a plug-in model. You’d keep the “Loan Partner” doctype lean and add a similarly lean 1:n “Loan Partnership” doctype to allow for various models per partner. Then you’d predefine a couple of plugins like:

- Pre-closure Charges Sharing
- Documentation Charges Sharing
- Payment (incl. check and direct debit) Bounces Sharing
- Insurance Premium Sharing
- Security EMI Sharing
- Legal and Recovery Fee Sharing
- Valuation Charges Sharing
- …

But a financial company using frappe/lending could also define other plugins to cater to its own needs.

You would receive a stable, seasoned, widely-adopted base functionality that is relatively easy to maintain, while each implementing user could define their own plugins catering to their needs.

Alternatively, if that’s way beyond what you’re planning to do at the moment and you do need co-lender functionality ASAP, then yes, better call it “Loan Co-lender.”

But from my point of view, it would be worth taking the more flexible approach now, even if the end result may take a few more months. We’re currently thinking of hiring a seasoned developer to further accelerate development, so we could offer a perk or two. I’m committed to redirecting all the money we’re saving on lackluster proprietary software into ERPNext instead. We just need to figure out what else needs to be done first… 😅

**Review by bosue — COMMENTED** [review]
♥️

**Comment by anandbaburajan** [comment]
@bosue we'll get back to you soon.

**Comment by anandbaburajan** [comment]
@bosue we've made a "shareables" table so that users can flexibly define and manage their own "shareables". Not sure yet if we'll need a _Loan Partnership_ to handle more complex sharing. We'll most probably restructure the doctype, add more generic fields, etc., so setting the doctype as beta.

**Comment by bosue** [comment]
This is nice, and much better than before.
While I think that at a later point we will need a _Loan Partnership_ doctype, I agree keeping it simple for now will be the better way forward! 👍

**Comment by bosue** [comment]
Just a question:

Partner and company ratio are added here to better support cases like:
1:2 (= 33,33333… % : 66,66666… %) shares (partner : company)
without any rounding hassles?

If this needs to be preserved through all calculations, and isn’t just an input helper, internally represented by a float, it _does_ complicate things quite a bit, but if necessary, it‘s necessary… 🤷🏻‍♂️

If using it as an input helper is enough, then we should automatically calculate, display and store the percentage share, while preserving the original input for subsequent use.

**Comment by anandbaburajan** [comment]
@bosue is your question regarding the `Partner Loan Share Ratio` and `Company Loan Share Ratio` fields or the `Partner Ratio` and `Company Ratio` fields in the child table?

**Comment by bosue** [comment]
@anandbaburajan: Yap, sorry for being a bit vague.

**Comment by anandbaburajan** [comment]
@bosue I still didn't get the clarification I was looking for 😄

**Comment by bosue** [comment]
@anandbaburajan:
LOOL, you‘re asking _this_ or _that_. My, ironically, very helpful answer: “Yap.” 😂

I‘m sorry. I was talking about the shareables child table and didn‘t even consider `Partner Loan Share Ratio` and `Company Loan Share Ratio`.

**Comment by anandbaburajan** [comment]
@bosue haha, okay. You're correct, the shareables table (and the whole Loan Partner doctype for that matter) needs more thinking. We're still exploring and will most probably restructure things, hence the doctype is in beta.

**Comment by bosue** [comment]
Then I would propose implementing the ratio only as an input helper to keep things simple behind the curtains.

So if somebody enters a Partner ratio of 1 and a Company ratio of 2, the Partner percentage is updated to 33,333, and this is what we‘d calculate with.

The original ratio 1 vs. 2 however is stored as well, so next time the user may easily change it to a 2 vs. 3 or a 2 vs. 5 ratio.

In the table we would only show the resulting percentage, so are saving two (or actually even three) columns of real estate, to fill with less redundant columns. When clicking on edit, the user has both input options, though.

**Pull request merged**
